;;; jenerated-blue-purple-theme.el --- Jenerated Blue Purple  -*- lexical-binding: t; -*-

;; Generated by jenerate.py from blue-purple-palette.toml. Don't edit
;; this file; change the palette or app-themes/emacs-theme/theme.el.tmpl.
;;
;; A custom theme: load it with M-x load-theme RET jenerated-blue-purple RET.
;; The code colors match the VS Code theme's. Faces for packages Emacs
;; hasn't loaded yet are kept until it does.

;;; Code:

(deftheme jenerated-blue-purple
  "The Blue Purple palette from Jenerated Themes.")

(custom-theme-set-faces
 'jenerated-blue-purple
 ;; The editor
 '(default ((t (:foreground "#DBDEE1" :background "#12131c"))))
 '(cursor ((t (:background "#5865F3"))))
 '(region ((t (:background "#3c4270" :extend t))))
 '(secondary-selection ((t (:background "#22243d" :extend t))))
 '(highlight ((t (:background "#1e2032"))))
 '(hl-line ((t (:background "#1a1c2a" :extend t))))
 '(fringe ((t (:foreground "#4b4d63" :background "#12131c"))))
 '(line-number ((t (:foreground "#4b4d63" :background "#12131c"))))
 '(line-number-current-line ((t (:foreground "#B5BAC1" :background "#1a1c2a"))))
 '(vertical-border ((t (:foreground "#2a2d40"))))
 '(window-divider ((t (:foreground "#2a2d40"))))
 '(fill-column-indicator ((t (:foreground "#222433"))))
 '(trailing-whitespace ((t (:background "#ED4246"))))
 '(shadow ((t (:foreground "#6b6f8a"))))
 '(link ((t (:foreground "#7289DA" :underline t))))
 '(link-visited ((t (:foreground "#9cb2fa" :underline t))))
 '(error ((t (:foreground "#ED4246" :weight bold))))
 '(warning ((t (:foreground "#FEE75D" :weight bold))))
 '(success ((t (:foreground "#57F288" :weight bold))))

 ;; Mode line, header line, minibuffer and tabs
 '(mode-line ((t (:foreground "#DBDEE1" :background "#0a0b13" :box (:line-width 1 :color "#2a2d40")))))
 '(mode-line-inactive ((t (:foreground "#6b6f8a" :background "#161825" :box (:line-width 1 :color "#2a2d40")))))
 '(mode-line-buffer-id ((t (:foreground "#ffffff" :weight bold))))
 '(header-line ((t (:foreground "#B5BAC1" :background "#0a0b13"))))
 '(minibuffer-prompt ((t (:foreground "#7289DA" :weight bold))))
 '(tab-bar ((t (:foreground "#6b6f8a" :background "#0a0b13"))))
 '(tab-bar-tab ((t (:foreground "#ffffff" :background "#12131c"))))
 '(tab-bar-tab-inactive ((t (:foreground "#6b6f8a" :background "#161825"))))
 '(tab-line ((t (:foreground "#6b6f8a" :background "#0a0b13"))))
 '(tooltip ((t (:foreground "#DBDEE1" :background "#191b28"))))

 ;; Searching and matching
 '(isearch ((t (:foreground "#12131c" :background "#EB459F" :weight bold))))
 '(isearch-fail ((t (:foreground "#ffffff" :background "#ED4246"))))
 '(lazy-highlight ((t (:foreground "#DBDEE1" :background "#22243d"))))
 '(match ((t (:foreground "#12131c" :background "#EB459F"))))
 '(show-paren-match ((t (:foreground "#ffffff" :background "#22243d" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#ffffff" :background "#ED4246"))))
 '(completions-common-part ((t (:foreground "#7289DA"))))
 '(completions-first-difference ((t (:foreground "#ffffff" :weight bold))))

 ;; Code, with the VS Code theme's colors
 '(font-lock-comment-face ((t (:foreground "#6b6f8a" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6b6f8a" :slant italic))))
 '(font-lock-doc-face ((t (:foreground "#6b6f8a" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#57F288"))))
 '(font-lock-keyword-face ((t (:foreground "#7289DA"))))
 '(font-lock-builtin-face ((t (:foreground "#5865F3"))))
 '(font-lock-function-name-face ((t (:foreground "#8593f5"))))
 '(font-lock-variable-name-face ((t (:foreground "#DBDEE1"))))
 '(font-lock-type-face ((t (:foreground "#4fd1c5"))))
 '(font-lock-constant-face ((t (:foreground "#EB459F"))))
 '(font-lock-number-face ((t (:foreground "#f2a65a"))))
 '(font-lock-property-name-face ((t (:foreground "#9cb2fa"))))
 '(font-lock-operator-face ((t (:foreground "#B5BAC1"))))
 '(font-lock-punctuation-face ((t (:foreground "#B5BAC1"))))
 '(font-lock-escape-face ((t (:foreground "#f2a65a"))))
 '(font-lock-preprocessor-face ((t (:foreground "#5865F3"))))
 '(font-lock-negation-char-face ((t (:foreground "#ED4246"))))
 '(font-lock-warning-face ((t (:foreground "#FEE75D" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#FEE75D"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#FEE75D"))))

 ;; Diffs
 '(diff-added ((t (:foreground "#57F288" :extend t))))
 '(diff-removed ((t (:foreground "#ED4246" :extend t))))
 '(diff-changed ((t (:foreground "#FEE75D" :extend t))))
 '(diff-header ((t (:foreground "#B5BAC1" :background "#161825"))))
 '(diff-file-header ((t (:foreground "#7289DA" :background "#161825" :weight bold))))
 '(diff-hunk-header ((t (:foreground "#4fd1c5" :background "#161825"))))

 ;; Terminal colors, for shells and compilation output (Emacs 28 and later)
 '(ansi-color-black ((t (:foreground "#1e1f2e" :background "#1e1f2e"))))
 '(ansi-color-red ((t (:foreground "#ED4246" :background "#ED4246"))))
 '(ansi-color-green ((t (:foreground "#57F288" :background "#57F288"))))
 '(ansi-color-yellow ((t (:foreground "#FEE75D" :background "#FEE75D"))))
 '(ansi-color-blue ((t (:foreground "#5865F3" :background "#5865F3"))))
 '(ansi-color-magenta ((t (:foreground "#EB459F" :background "#EB459F"))))
 '(ansi-color-cyan ((t (:foreground "#4fd1c5" :background "#4fd1c5"))))
 '(ansi-color-white ((t (:foreground "#DBDEE1" :background "#DBDEE1"))))
 '(ansi-color-bright-black ((t (:foreground "#4b4d63" :background "#4b4d63"))))
 '(ansi-color-bright-red ((t (:foreground "#f47a7d" :background "#f47a7d"))))
 '(ansi-color-bright-green ((t (:foreground "#8bf6ac" :background "#8bf6ac"))))
 '(ansi-color-bright-yellow ((t (:foreground "#fdf08a" :background "#fdf08a"))))
 '(ansi-color-bright-blue ((t (:foreground "#8593f5" :background "#8593f5"))))
 '(ansi-color-bright-magenta ((t (:foreground "#f18cbf" :background "#f18cbf"))))
 '(ansi-color-bright-cyan ((t (:foreground "#8be3da" :background "#8be3da"))))
 '(ansi-color-bright-white ((t (:foreground "#ffffff" :background "#ffffff")))))

;; Terminal colors for Emacs before 28, which didn't have faces for them.
(custom-theme-set-variables
 'jenerated-blue-purple
 '(ansi-color-names-vector ["#1e1f2e" "#ED4246" "#57F288" "#FEE75D"
                           "#5865F3" "#EB459F" "#4fd1c5" "#DBDEE1"]))

(provide-theme 'jenerated-blue-purple)

;;; jenerated-blue-purple-theme.el ends here
