// Jenerated Blue Purple: an Insomnia theme generated by jenerate.py from
// blue-purple-palette.toml. Don't edit this file; change the palette or
// app-themes/insomnia-theme/index.js.tmpl.
//
// "surprise" is Insomnia's accent color (the Send button, for one), and each
// foreground color is the text drawn on the background color of the same
// name. The plugin needs no permissions: it only provides this theme.

module.exports.themes = [
  {
    name: 'jenerated-blue-purple',
    displayName: 'Jenerated Blue Purple',
    theme: {
      background: {
        default: '#12131c',
        success: '#57F288',
        notice: '#FEE75D',
        warning: '#f2a65a',
        danger: '#ED4246',
        surprise: '#5865F3',
        info: '#4fd1c5',
      },
      foreground: {
        default: '#DBDEE1',
        success: '#12131c',
        notice: '#12131c',
        warning: '#12131c',
        danger: '#12131c',
        surprise: '#ffffff',
        info: '#12131c',
      },
      highlight: {
        default: '#6b6f8a',
        xxs: 'rgba(107, 111, 138, 0.05)',
        xs: 'rgba(107, 111, 138, 0.1)',
        sm: 'rgba(107, 111, 138, 0.2)',
        md: 'rgba(107, 111, 138, 0.4)',
        lg: 'rgba(107, 111, 138, 0.6)',
        xl: 'rgba(107, 111, 138, 0.8)',
      },
      styles: {
        appHeader: {
          background: { default: '#0a0b13' },
        },
        sidebar: {
          background: { default: '#161825' },
          foreground: { default: '#B5BAC1' },
        },
        dialog: {
          background: { default: '#191b28' },
        },
        dropdown: {
          background: { default: '#191b28' },
        },
        tooltip: {
          background: { default: '#191b28' },
        },
        editor: {
          background: { default: '#12131c' },
        },
        link: {
          foreground: { default: '#7289DA' },
        },
        transparentOverlay: {
          background: { default: 'rgba(10, 11, 19, 0.8)' },
        },
      },
    },
  },
];
