# Jenerated Blue Purple: PowerShell colors, generated by jenerate.py from
# blue-purple-palette.toml. Don't edit this file; change the palette or
# app-themes/pwsh-theme/colors.ps1.tmpl.
#
# Your PowerShell profile loads this. It colors the command line as you type
# (PSReadLine) and PowerShell's own output ($PSStyle: tables, errors,
# warnings, progress bars and file listings), with 24-bit colors. Each color
# is set on its own and skipped if your version doesn't have it, so older
# PowerShell and PSReadLine versions get every color they know.

# 24-bit color codes, from 0xRRGGBB: text color, and background color.
$jeneratedFg = { param([int]$rgb) "$([char]27)[38;2;$(($rgb -shr 16) -band 255);$(($rgb -shr 8) -band 255);$($rgb -band 255)m" }
$jeneratedBg = { param([int]$rgb) "$([char]27)[48;2;$(($rgb -shr 16) -band 255);$(($rgb -shr 8) -band 255);$($rgb -band 255)m" }
$jeneratedBold = "$([char]27)[1m"

# The command line, colored like code in the editor themes.
if (Get-Command Set-PSReadLineOption -ErrorAction SilentlyContinue) {
    $jeneratedColors = @{
        Default                = & $jeneratedFg 0xDBDEE1
        Comment                = & $jeneratedFg 0x6b6f8a
        Keyword                = & $jeneratedFg 0x7289DA
        String                 = & $jeneratedFg 0x57F288
        Operator               = & $jeneratedFg 0xB5BAC1
        Variable               = & $jeneratedFg 0x9cb2fa
        Command                = & $jeneratedFg 0x8593f5
        Parameter              = & $jeneratedFg 0xf2a65a
        Type                   = & $jeneratedFg 0x4fd1c5
        Number                 = & $jeneratedFg 0xf2a65a
        Member                 = & $jeneratedFg 0x9cb2fa
        Emphasis               = & $jeneratedFg 0xEB459F
        Error                  = & $jeneratedFg 0xED4246
        ContinuationPrompt     = & $jeneratedFg 0x6b6f8a
        Selection              = (& $jeneratedBg 0x3c4270) + (& $jeneratedFg 0xDBDEE1)
        InlinePrediction       = & $jeneratedFg 0x4b4d63
        ListPrediction         = & $jeneratedFg 0x6b6f8a
        ListPredictionSelected = & $jeneratedBg 0x22243d
        ListPredictionTooltip  = & $jeneratedFg 0x6b6f8a
    }
    foreach ($jeneratedName in $jeneratedColors.Keys) {
        try { Set-PSReadLineOption -Colors @{ $jeneratedName = $jeneratedColors[$jeneratedName] } } catch { }
    }
}

# PowerShell's output (7.2 and later).
if ($PSStyle) {
    $jeneratedStyles = @{
        'Formatting.FormatAccent'           = (& $jeneratedFg 0x5865F3) + $jeneratedBold
        'Formatting.TableHeader'            = (& $jeneratedFg 0x5865F3) + $jeneratedBold
        'Formatting.CustomTableHeaderLabel' = & $jeneratedFg 0x7289DA
        'Formatting.ErrorAccent'            = (& $jeneratedFg 0xf2a65a) + $jeneratedBold
        'Formatting.Error'                  = & $jeneratedFg 0xED4246
        'Formatting.Warning'                = & $jeneratedFg 0xFEE75D
        'Formatting.Verbose'                = & $jeneratedFg 0x8593f5
        'Formatting.Debug'                  = & $jeneratedFg 0x6b6f8a
        'Formatting.FeedbackName'           = & $jeneratedFg 0x5865F3
        'Formatting.FeedbackText'           = & $jeneratedFg 0xDBDEE1
        'Formatting.FeedbackAction'         = & $jeneratedFg 0x8593f5
        'Progress.Style'                    = & $jeneratedFg 0x5865F3
        'FileInfo.Directory'                = (& $jeneratedFg 0x8593f5) + $jeneratedBold
        'FileInfo.SymbolicLink'             = & $jeneratedFg 0x4fd1c5
        'FileInfo.Executable'               = (& $jeneratedFg 0x57F288) + $jeneratedBold
    }
    foreach ($jeneratedName in $jeneratedStyles.Keys) {
        $jeneratedGroup, $jeneratedProperty = $jeneratedName.Split('.')
        try { $PSStyle.$jeneratedGroup.$jeneratedProperty = $jeneratedStyles[$jeneratedName] } catch { }
    }
    # Archives in orange, PowerShell scripts in yellow, as PowerShell groups them.
    foreach ($jeneratedExtension in '.zip', '.tgz', '.gz', '.tar', '.nupkg', '.cab', '.7z') {
        try { $PSStyle.FileInfo.Extension[$jeneratedExtension] = (& $jeneratedFg 0xf2a65a) + $jeneratedBold } catch { }
    }
    foreach ($jeneratedExtension in '.ps1', '.psd1', '.psm1', '.ps1xml') {
        try { $PSStyle.FileInfo.Extension[$jeneratedExtension] = (& $jeneratedFg 0xFEE75D) + $jeneratedBold } catch { }
    }
}

Remove-Variable -Name jeneratedFg, jeneratedBg, jeneratedBold, jeneratedColors, jeneratedStyles, jeneratedName, jeneratedGroup, jeneratedProperty, jeneratedExtension -ErrorAction SilentlyContinue
