# Jenerated Blue Purple: fzf colors generated by jenerate.py from
# blue-purple-palette.toml. Don't edit this file; change the palette or
# app-themes/fzf-theme/fzf.sh.tmpl.
#
# Loaded from ~/.bashrc or ~/.zshrc, it adds the palette's colors to
# FZF_DEFAULT_OPTS, after any options of your own. It only uses color names
# fzf has had since 0.29 (Ubuntu 22.04): older versions refuse a name they
# don't know, and ignore all the colors with it.

_jenerated_fzf_colors='--color=fg:#B5BAC1,bg:#12131c,hl:#EB459F,fg+:#ffffff,bg+:#22243d,hl+:#EB459F,gutter:#12131c,query:#DBDEE1,disabled:#4b4d63,info:#6b6f8a,border:#2a2d40,prompt:#5865F3,pointer:#5865F3,marker:#57F288,spinner:#7289DA,header:#8593f5,preview-fg:#DBDEE1,preview-bg:#12131c'

# Add them once, even when a shell started from this one loads this again.
case " ${FZF_DEFAULT_OPTS:-} " in
  *" $_jenerated_fzf_colors "*) ;;
  *) export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }$_jenerated_fzf_colors" ;;
esac
unset _jenerated_fzf_colors
