# Jenerated Blue Purple: zsh colors generated by jenerate.py from
# blue-purple-palette.toml. Don't edit this file; change the palette or
# app-themes/zsh-theme/colors.zsh.tmpl.
#
# ~/.zshrc loads this. It colors the command line as you type, for
# zsh-syntax-highlighting, and the suggested text of zsh-autosuggestions.
# (fast-syntax-highlighting has a theme file of its own.) Without either
# plugin, it does nothing but set a few variables.

# The colors are #rrggbb. Terminals without 24-bit color get the nearest of
# the colors they have, through zsh's nearcolor module.
[[ $COLORTERM == *(24bit|truecolor)* ]] || zmodload zsh/nearcolor 2>/dev/null

# zsh-syntax-highlighting: set whether this loads before or after the plugin
# (the plugin keeps styles that are already set).
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#ED4246,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#7289DA'
# Commands, in the color of functions in the other themes.
ZSH_HIGHLIGHT_STYLES[alias]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[function]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[command]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#8593f5,underline'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#8593f5'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#4fd1c5,underline'
# Paths, globs and history.
ZSH_HIGHLIGHT_STYLES[path]='fg=#DBDEE1,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#FEE75D'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#EB459F'
# Strings, and the variables and escapes in them.
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#57F288'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#57F288'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#57F288'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#f2a65a'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#f2a65a'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#f2a65a'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#f2a65a'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#EB459F'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#EB459F'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#EB459F'
# Options, like the parameters in the other themes.
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#f2a65a'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#f2a65a'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#f2a65a'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#f2a65a'
# Operators, assignments and comments.
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#B5BAC1'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#B5BAC1'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#9cb2fa'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#6b6f8a'

# zsh-autosuggestions: the suggested rest of the line, dimmed like comments.
typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#6b6f8a'
